### ISSUE TITLE
flops calculation for the shortcut layer when stride==1 is not considered?

### ISSUE THREAD

**Issue by peymanrostami** [irwinherrmann/stochastic-gates#2]
Hi there,

Thank you very much for sharing the codes.

I have a question regarding the calculation of FLOPS.

in this [this line](https://github.com/irwinherrmann/stochastic-gates/blob/14828bf708831de0a0d5ca7b202403bb26b94ff9/models/resnet_filter.py#L690) in your code you do not consider the number of flops of the shortcut layer (i.e. ` shortcut_layer_gflops` in your code ) for the case of `stride==1`. 

may I ask you to kindly explain the reason?

**Comment by irwinherrmann** [comment]
Seems like a bug in the _cifar model. Please feel free to submit a patch.
